---
language: python

before_install:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-daily
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y freecad freecad-doc
  - gcc --version
  - g++ --version
  - python ./setup.py install
  - pip install coverage
  - pip install coveralls

script:
  coverage run --source=cadquery python ./runtests.py

after_success:
  coveralls
